# Generated by Django 4.2.5 on 2023-09-23 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedlessons',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='related_product',
            field=models.ManyToManyField(related_name='lessons', to='products.product'),
        ),
        migrations.AddField(
            model_name='allowedproducts',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_to', to='products.product'),
        ),
        migrations.AddField(
            model_name='allowedproducts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
