# Generated by Django 4.2.5 on 2023-09-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedproducts',
            old_name='user_id',
            new_name='user',
        ),
    ]
